version: "3.9"

services:
  front:
    # container_name: react
    build: .
    command: npm start
    volumes:
      - .:/code
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    